---

- import_playbook: bootstrap.yml
  tags:
    - bootstrap
- import_playbook: database.yml
- import_playbook: solr.yml
- import_playbook: webserver.yml
- import_playbook: fedora.yml
- import_playbook: triplestore.yml
- import_playbook: cantaloupe.yml
- import_playbook: crayfish.yml
- import_playbook: activemq.yml
- import_playbook: karaf.yml
- import_playbook: post-install.yml
