---

islandora_distro: "ubuntu/bionic64"
# Change selinux status to permissive
disable_selinux: yes

islandora_extra_ubuntu_packages:
  - wget
  - curl
  - htop
  - tree
  - zsh
  - fish
  - unzip
  - build-essential
  - vim
  - python3-mysqldb

islandora_extra_centos_packages:
  - wget
  - curl
  - tree
  - zsh
  - unzip
  - vim
  - make
  - automake
  - gcc
  - gcc-c++
  - kernel-devel

postgresql_user: postgres

claw_db: "mysql"
db_port: "3306"
drupal_db_user: drupal8
drupal_db_name: drupal8
drupal_db_backend: "{{ claw_db }}" 
drupal_db_host: "{{ db_host }}" 
drupal_db_port: "{{ db_port }}" 
mysql_root_password: "{{ islandora_db_root_password }}"
mysql_root_username: "root"

broker_url: "tcp://{{  hostvars[groups['karaf'][0]].ansible_host }}:61616"	
stomp_broker_url: "tcp://{{  hostvars[groups['karaf'][0]].ansible_host }}:61613"	



mysql_users:
  - name: "{{ drupal_db_user }}"
    password: "{{ drupal_db_password }}"
    priv: "{{ drupal_db_name }}.*:ALL"
    login_host: "{{ drupal_db_host }}"
    login_port: "{{ drupal_db_port }}"
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password:  "{{ mysql_root_password }}"
    host: "%"
     

# Used by both the webserver and crayfish role for CentOS.
php_enablerepo: "remi-php72"
php_packages_state: "latest"
